version: '3'

services:
  postgres:
    image: postgres:11.7
    container_name: postgres
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./environment/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      - POSTGRES_PASSWORD=$TYPEORM_PASSWORD

  template:
    image: template
    build: .
    ports: 
      - 80:80
    environment: 
      - PORT=80
